// Auto-generated by LibreLane
module MMU(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input control,
  input[31:0] data_arr,
  input[31:0] wt_arr,
  output[127:0] acc_out
);
endmodule
